version: '3'
services:
  langchain-chat-app:
    image: aironman/embedchain-streamlit-app:latest
    build: ./app
    command: streamlit run demo_app/main.py --server.port 8501
    volumes:
      - ./demo_app/:/app/demo_app
    ports:
      - "8501:8501"
